name: Java CI with Maven

# Указываем триггеры для запуска workflow
on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании pull request в ветку main

jobs:
  build:
    # ОС, на которой будет запускаться сборка
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем JDK (в данном случае JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Укажите нужную версию JDK
          distribution: 'temurin'  # Это одна из популярных реализаций JDK

      # Шаг 3: Кешируем зависимости Maven, чтобы ускорить сборку
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Шаг 4: Устанавливаем зависимости Maven
      - name: Install dependencies
        run: mvn install -DskipTests

      # Шаг 5: Устанавливаем Chrome для тестов
      - name: Install Chrome browser
        run: sudo apt-get install -y google-chrome-stable

      # Шаг 6: Запускаем тесты
      - name: Run tests
        env:
          CI: true  # Устанавливаем переменную окружения для активации headless режима
        run: mvn test
